# Generated by Django 4.2.6 on 2024-01-18 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_reviewmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewModel',
            new_name='RatingModel',
        ),
    ]
