# Generated by Django 4.2.6 on 2024-01-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_address'),
        ('author', '0002_hotelbookingdata_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookingdata',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking', to='posts.post'),
        ),
    ]
